### ISSUE TITLE
appear in the list of apps to share address

### ISSUE THREAD

**Issue by SimpleHomeUser** [DanielBarnett714/AddressToGPS#8]
Hello,

Thank you for this app that is very usefull for me.
The only thing is when I click on an address for example in my contacts, I have a list of app to open it with.
It would be great if your app appearred in the list.

Or when I want to share an address from another app, it would help if your app appeard in the list ..

I don't know how you tell android to add an app in the list of addresses linked apps, but I hope it's not to difficult.

**Comment by DanielBarnett714** [comment]
It should theoretically be easy, and it's called an android intent. There are a lot of things I would like to add, it's just I'm in school fill time and working so I'm pretty overwhelmed at the moment. Spring break I think is when I'm going to get a lot done. I have a bunch of new ideas and suggestions like this are great. 
Thank you and sorry it's been a while since an update.

**Comment by DanielBarnett714** [comment]
*school full time. Not fill time. I have no time haha.
